---
- name: Install postgresql packages
  apt: name={{ item }} state=installed
  with_items:
    - postgresql
    - postgresql-client
    - python-psycopg2

- name: Create crrr postgresql databases
  sudo: True
  sudo_user: postgres
  postgresql_db: name={{ db }}-{{ item }}
  with_items:
    - dev
    - staging
    - production

- name: Create crrr postgresql user
  sudo: True
  sudo_user: postgres
  postgresql_user: db={{ db }}-{{ item }}
                   user={{ db_user }}
                   password="{{ lookup('password', '../../../credentials/postgresql length=15') }}"
                   priv=ALL
                   role_attr_flags=SUPERUSER
  with_items:
    - dev
    - staging
    - production
