---
- name: Install postgresql packages
  apt: name={{ item }} state=installed
  with_items:
    - postgresql
    - postgresql-client
    - python-psycopg2
    - postgresql-server-dev-9.1

- name: Create crrr postgresql databases
  sudo: True
  sudo_user: postgres
  postgresql_db: name={{ app_name }}

- name: Create crrr postgresql user
  sudo: True
  sudo_user: postgres
  postgresql_user: db={{ app_name }}
                   user={{ db_user }}
                   password="{{ lookup('password', '../../../credentials/postgresql length=15') }}"
                   priv=ALL
                   role_attr_flags=SUPERUSER
