---

- name: Install ufw
  apt: name=ufw state=latest
  tags: ufw

- name: Allow applications
  command: ufw allow {{ item }}
  register: ufw_out
  changed_when: "'Rules updated' in ufw_out.stdout"
  with_items:
    - 'OpenSSH'
    - 'Dovecot\ Secure\ IMAP'
    - 'Dovecot\ Secure\ POP3'
    - 'Nginx\ Full'
    - 'mosh'
    - 'Postfix\ SMTPS'
    - 'Postfix\ Submission'
    - 'Postfix'
  tags: ufw

- name: Turn on ufw
  command: ufw enable
  async: 5
  poll: 1
  tags: ufw

- name: Make sure ufw is set to run at boot
  service: name=ufw state=started enabled=yes
  tags: ufw
